In [1]:
import numpy as np

rng = np.random.RandomState(10) 
# everytime it will generate same seq of random numbers

In [2]:
x = rng.rand(1000000)
y = rng.rand(1000000)

%timeit x + y

100 loops, best of 3: 13.8 ms per loop

## pandas eval
* This rely on Numexpr package without costly allocation of intermediate placeholder arrays
* Supports all arithmetic opeartions
* Comparision Oparations
* Bitwise operations
* Object attributes indexing

In [6]:
import pandas as pd

nrows, ncols = 100000, 100

rng = np.random.RandomState(42)

df1, df2, df3, df4 = (pd.DataFrame(rng.rand(nrows, ncols))
                      for i in range(4))

In [8]:
%timeit df1 + df2 + df3 + df4

1 loop, best of 3: 481 ms per loop

In [10]:
%timeit pd.eval('df1 + df2 + df3 + df4')

1 loop, best of 3: 208 ms per loop

In [12]:
%timeit(df1 < df2) & (df2 <= df3) & (df3 != df4)

1 loop, best of 3: 1.6 s per loop

In [13]:
%timeit pd.eval('df1 < df2 <= df3 != df4')

1 loop, best of 3: 217 ms per loop

In [14]:
%timeit (df1 < 0.5) & (df2 < 0.5) | (df3 < df4)
%timeit pd.eval('(df1 < 0.5) & (df2 < 0.5) | (df3 < df4)')

1 loop, best of 3: 1.76 s per loop
1 loop, best of 3: 238 ms per loop

#### DataFrame.eval() for Column-Wise Opearation

In [15]:
df = pd.DataFrame(rng.rand(1000, 3), columns=['A', 'B', 'C'])
df.head()

          A         B         C
0  0.615875  0.525167  0.047354
1  0.330858  0.412879  0.441564
2  0.689047  0.559068  0.230350
3  0.290486  0.695479  0.852587
4  0.424280  0.534344  0.245216

In [25]:
res = (df['A'] + df['B']) / (df['C'] - 1)

In [27]:
## Not sure why is this performing o bad
res2 = pd.eval("(df.A+ df.B) / (df.C - 1)")

In [31]:
res - res2

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6      0.0
7      0.0
8      0.0
9      0.0
10     0.0
11     0.0
12     0.0
13     0.0
14     0.0
15     0.0
16     0.0
17     0.0
18     0.0
19     0.0
20     0.0
21     0.0
22     0.0
23     0.0
24     0.0
25     0.0
26     0.0
27     0.0
28     0.0
29     0.0
      ...
970    0.0
971    0.0
972    0.0
973    0.0
974    0.0
975    0.0
976    0.0
977    0.0
978    0.0
979    0.0
980    0.0
981    0.0
982    0.0
983    0.0
984    0.0
985    0.0
986    0.0
987    0.0
988    0.0
989    0.0
990    0.0
991    0.0
992    0.0
993    0.0
994    0.0
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
dtype: float64

#### DataFrame Query Method

In [34]:
df.query('A < 0.5 and B > 0.5')

            A         B         C
3    0.290486  0.695479  0.852587
4    0.424280  0.534344  0.245216
5    0.111085  0.566276  0.464323
6    0.181763  0.511544  0.368457
7    0.048330  0.779839  0.459669
16   0.448659  0.874896  0.444728
21   0.142193  0.585808  0.360283
22   0.369002  0.869797  0.013812
23   0.239374  0.816387  0.560361
24   0.013722  0.813868  0.832219
41   0.398415  0.778884  0.115655
49   0.322639  0.722052  0.739568
51   0.024199  0.618790  0.355797
57   0.125272  0.675219  0.793796
66   0.164486  0.641220  0.367754
69   0.322742  0.813945  0.828293
71   0.123911  0.657211  0.969346
73   0.410247  0.887447  0.231525
75   0.482933  0.538566  0.196487
83   0.275565  0.974806  0.914719
87   0.209609  0.949398  0.695166
90   0.328885  0.942053  0.811357
100  0.379105  0.619775  0.128879
108  0.301938  0.542352  0.988515
116  0.039100  0.635213  0.221909
123  0.149184  0.862237  0.014469
124  0.238871  0.936328  0.540506
126  0.071847  0.539336  0.735446
131  0.273798  0.523611  0.573905
133  0.442882  0.563377  0.210237
..        ...       ...       ...
870  0.178208  0.688170  0.461956
871  0.054143  0.713619  0.581227
877  0.264149  0.534285  0.038475
886  0.100248  0.534026  0.572061
890  0.407157  0.807704  0.001172
896  0.256090  0.514205  0.471564
897  0.078803  0.671919  0.877495
901  0.025002  0.742965  0.638428
902  0.227652  0.944001  0.953901
904  0.259557  0.701744  0.459842
905  0.281249  0.731838  0.252684
907  0.220794  0.761913  0.761529
910  0.268661  0.826027  0.543592
911  0.148043  0.834007  0.083861
922  0.425449  0.757807  0.477264
941  0.273042  0.939044  0.890068
945  0.399699  0.893224  0.156696
950  0.454681  0.688249  0.950359
966  0.232190  0.844586  0.196665
969  0.200869  0.598454  0.695883
973  0.459376  0.633276  0.658403
975  0.119329  0.818229  0.636777
978  0.044733  0.756966  0.103255
986  0.081072  0.963388  0.458573
987  0.351390  0.705973  0.305346
988  0.348217  0.718888  0.592094
991  0.381927  0.504305  0.422546
994  0.039172  0.931786  0.210162
996  0.223362  0.748549  0.550715
999  0.254963  0.861045  0.704858

[246 rows x 3 columns]