In [1]:
import pandas as pd

In [5]:
wp = pd.read_csv(r'C:\Users\ZekeLabs\Downloads\Working_Population_according_to_2011_Census.csv')

In [7]:
wp.head()

,India/State/Union Territory,Total Population_Persons,Main Workers_Persons,Percentage of main Workers to total Population_2001_Persons,Percentage of main Workers to total Population_2011_Persons,Total Population_Males,Main Workers_Males,Percentage of main Workers to total Population_2001_Males,Percentage of main Workers to total Population_2011_Males,Total Population_Females,Main Workers_Females,Percentage of main Workers to total Population_2001_Females,Percentage of main Workers to total Population_2011_Females
0,India,1210569573,362446420,30.43,29.94,623121843,273149359,45.13,43.84,587447730,89297061,14.67,15.20
1,Andhra Pradesh,84580777,33037378,38.11,39.06,42442146,21460081,50.50,50.56,42138631,11577297,25.44,27.47
2,Arunachal Pradesh,1383727,478721,37.80,34.60,713912,301109,46.11,42.18,669815,177612,28.50,26.52
3,Assam,31205576,8687123,26.69,27.84,15939443,7034642,42.45,44.13,15266133,1652481,9.82,10.82
4,Bihar,104099452,21359611,25.37,20.52,54278157,17270690,40.49,31.82,49821295,4088921,8.91,8.21

In [11]:
from bokeh.charts import Bar, output_file, show #use output_notebook to visualize it in notebook
# prepare data (dummy data)
data = {"y": [1, 2, 3, 4, 5]}
# Output to Line.HTML
output_file("lines1.html", title="line plot example") #put output_notebook() for notebook
# create a new line chat with a title and axis labels
p = Bar(data, title="Line Chart Example", xlabel='x', ylabel='values', width=400, height=400)
# show the results
show(p)

In [12]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots( nrows=1, ncols=1 )  # create figure & 1 axis
ax.plot([0,1,2], [10,20,3])
fig.savefig('to.png')   # save the figure to file
plt.close(fig)    # close the figure